spring:
  security:
    user:
      name:
      password:
      roles:
  jwt:
    secret:
  datasource:
    driver-class-name:
    url:
    username:
    password:
    platform:
    initialize:
  h2:
    console:
      enable:
      path:
  jpa:
    hibernate:
      ddl-auto:
      show-sql:
      open-in-view:
  devtools:
    restart:
      enabled:
client:
  url:
cookie:
  set:
    secure: